Repository MNK-photoday/photoday, pull requests merged in 2023-03, with the labels that each got.

#12 [Feat] Route, Directory, Package
  client/package.json
  client/public/manifest.json
  client/src/App.tsx
  client/src/Styles/GlobalStyles.tsx
  client/src/components/common/Button/Button.tsx
  client/src/components/common/Footer/Footer.tsx
  client/src/components/common/Header/Header.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/routes/Route.tsx
  client/yarn.lock
Labels: 아현

#22 [Style] Layout, GlobalStyle
  client/src/styles/GlobalStyles.tsx
  client/src/styles/Layout.tsx
Labels: 정호, style

#30 [Design] Main Page Layout 구현
  client/src/components/common/Footer/Footer.styles.tsx
  client/src/components/common/Footer/Footer.tsx
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
  client/src/styles/Layout.tsx
  client/src/styles/ResetCss.tsx
Labels: Design

#35 [Design] Header, SearchBar
  client/package.json
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/styles/ResetCss.tsx
  client/yarn.lock
Labels: 정호, Design

#41 [Design] Main Content Component 구현
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Design

#46 [Design] Login Page 구현
  client/src/App.tsx
  client/src/components/Login/Button/Button.styles.tsx
  client/src/components/Login/GoogleBtn/Button.styles.tsx
  client/src/components/Login/GoogleBtn/GoogleBtn.tsx
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LinkText/LinkText.styles.tsx
  client/src/components/Login/LinkText/LinkText.tsx
  client/src/components/Login/Login/Login.styles.tsx
  client/src/components/Login/Login/Login.tsx
  client/src/components/Login/LoginLogo/LoginLogo.styles.tsx
  client/src/components/Login/LoginLogo/LoginLogo.tsx
  client/src/components/Login/Logo/Logo.tsx
  client/src/components/Login/Signup/Signup.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/routes/Route.tsx
Labels: 아현, Design

#44 [Design] Account Recovery Page 구현
  client/src/pages/AccountRecovery/AccountRecovery.tsx
Labels: 아현, Design

#51 [Design] Sign up 페이지 모달 구현
  client/src/components/Login/GoogleBtn/Button.styles.tsx
  client/src/components/Login/GoogleBtn/GoogleBtn.tsx
  client/src/components/Login/GoogleButton/GoogleButton.styles.tsx
  client/src/components/Login/GoogleButton/GoogleButton.tsx
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LinkText/LinkText.styles.tsx
  client/src/components/Login/LinkText/LinkText.tsx
  client/src/components/Login/LoginLogo/LoginLogo.styles.tsx
  client/src/components/Login/LoginLogo/LoginLogo.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.styles.tsx
  client/src/pages/Signup/Signup.tsx
Labels: 아현, Design

#58 [Desgin] Main Page 구현
  client/src/components/common/Button/Button.style.tsx
  client/src/components/common/Button/Button.tsx
  client/src/components/common/Card/Card.style.tsx
  client/src/components/common/Card/Card.tsx
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Design

#59 [Design] Upload Page 구현
  client/src/pages/Upload/Upload.styles.tsx
  client/src/pages/Upload/Upload.tsx
Labels: 은수, Design

#63 [Design] Main Page 구현 및 Card 파일명 수정
  client/src/components/common/Card/Card.tsx
  client/src/components/common/Image/ImageCard.style.tsx
  client/src/components/common/Image/ImageCard.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Design

#84 [Feature] Header Modal Component, Header Component 구현
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderModal.styles.tsx
  client/src/components/common/Header/HeaderModal.tsx
Labels: 정호, Design

#82 [Feature] 로그인 유효성 검사 기능 구현
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LoginValidationLogic/LoginValidationLogic.tsx
  client/src/components/common/Button/Button.style.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
Labels: 아현, Feature

#89 [Fesign, Package] Package 의존성 삭제, User Page 레이아웃 구현
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/assets/imgs/kungyaImage.png
  client/src/assets/imgs/userDefaultProfile.png
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/User/User.styles.tsx
  client/src/pages/User/User.tsx
Labels: 아현, Design

#98 [Design] Search Page 구현
  client/src/App.tsx
  client/src/pages/Search/Search.styled.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Feature, Design

#107 [Design] User Page 구현
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserInfoArea/UserInfoInput/UserInfoInput.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoInput/UserInfoInput.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.styles.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.styles.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/components/common/Button/Button.style.tsx
  client/src/components/common/Button/Button.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/User/User.styles.tsx
  client/src/pages/User/User.tsx
  client/src/styles/ResetCss.tsx
Labels: 아현, Design

#112 [Design] 404 Not Found Page 구현
  client/src/App.tsx
  client/src/pages/ErrorPage/ErrorPage.style.tsx
  client/src/pages/ErrorPage/ErrorPage.tsx
Labels: 정호, Design

#122 [Design] Scrollbar Custom 작업
  client/src/pages/Main/Main.styles.tsx
  client/src/styles/ResetCss.tsx
Labels: 정호, Design

#125 [Feature] 유저 페이지 비밀번호 유효성 검사 기능 구현
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LoginValidationLogic/LoginValidationLogic.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserInfoArea/UserInfoInput/UserInfoInput.tsx
  client/src/components/User/UserInfoArea/UserInfoTextarea/UserInfoTextarea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoTextarea/UserInfoTextarea.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/User/User.tsx
Labels: 아현, Feature

#131 [Feature] Upload page 1차 구현
  client/src/components/Upload/Tag/TagItem.tsx
  client/src/components/Upload/Tag/TagList.tsx
  client/src/pages/Upload/Upload.styles.tsx
  client/src/pages/Upload/Upload.tsx
Labels: 은수, Feature

#132 [Design] ImageCard hover 작업
  client/src/components/common/ImageCard/ImageCard.style.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
Labels: 정호, Design

#138 [Design] Follow Modal 구현
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LoginValidationLogic/LoginValidationLogic.tsx
  client/src/components/User/UserFollwModal/ModalListItem.styles.tsx
  client/src/components/User/UserFollwModal/ModalListItem.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.styles.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.styles.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/User/User.tsx
Labels: 아현, Design

#139 [Design] Detail page 세부 디자인 구현
  client/src/App.tsx
  client/src/pages/Detail/Detail.styles.tsx
  client/src/pages/Detail/Detail.tsx
Labels: 은수, Design

#143 [Design] Main Skeleton 적용
  client/src/components/common/Skeleton/MainSkeleton.tsx
  client/src/components/common/Skeleton/Skeleton.style.tsx
  client/src/components/common/Skeleton/Skeleton.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Design

#144 [Feature] SearchBar 검색어 state 관리
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/pages/Search/Search.styles.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Design

#151 [Design] ImageCard props 적용
  client/src/components/common/ImageCard/ImageCard.styles.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Design

#152 [Feature] Sign up 기능 개발
  client/.gitignore
  client/src/api/Signup.ts
  client/src/components/Login/Input/Input.styles.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/tsconfig.json
Labels: 아현, Feature

#157 Feat/logging
  server/build.gradle
  server/src/main/java/com/photoday/photoday/PhotodayApplication.java
  server/src/main/java/com/photoday/photoday/excpetion/ExceptionControllerAdvice.java
  server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
  server/src/main/java/com/photoday/photoday/image/service/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/service/S3ServiceImpl.java
  server/src/main/java/com/photoday/photoday/logging/Aspect.java
  server/src/main/java/com/photoday/photoday/logging/PointCuts.java
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/controller/AuthController.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/photoday/photoday/security/service/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/utils/UserDataResponder.java
  server/src/main/java/com/photoday/photoday/tag/controller/TagController.java
  server/src/main/java/com/photoday/photoday/tag/service/TagServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/service/UserServiceImpl.java
  server/src/main/resources/application.yml
  server/src/test/java/com/photoday/photoday/follow/controller/FollowControllerTest.java
  server/src/test/java/com/photoday/photoday/helper/security/SecurityTestHelper.java
  server/src/test/java/com/photoday/photoday/image/controller/ImageControllerTest.java
  server/src/test/java/com/photoday/photoday/image/mapper/ImageMapperTest.java
  server/src/test/java/com/photoday/photoday/image/service/ImageServiceImplTest.java
  server/src/test/java/com/photoday/photoday/tag/controller/TagControllerTest.java
  server/src/test/java/com/photoday/photoday/user/controller/UserControllerTest.java
  server/src/test/java/com/photoday/photoday/user/service/UserServiceImplTest.java
Labels: 영롱, Feature

#155 [Feature] Login 기능 개발 + Redux 생성
  client/src/api/Login.ts
  client/src/api/Signup.ts
  client/src/api/auth.ts
  client/src/index.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/store/authSlice.ts
  client/src/store/store.ts
Labels: 아현, Feature

#162 [Docs] 테스트 코드 DB 설정 #161
  server/Dockerfile
  server/docker-compose.yml
  server/src/test/resources/application.yml
Labels: 민수

#165 [Feat, Fix] Feat/mail
  server/src/main/java/com/photoday/photoday/excpetion/ExceptionControllerAdvice.java
  server/src/main/java/com/photoday/photoday/mail/config/EmailConfiguration.java
  server/src/main/java/com/photoday/photoday/mail/config/EmailSendable.java
  server/src/main/java/com/photoday/photoday/mail/config/EmailSender.java
  server/src/main/java/com/photoday/photoday/mail/config/SimpleEmailSendable.java
  server/src/main/java/com/photoday/photoday/mail/developer/DeveloperApplicationEvent.java
  server/src/main/java/com/photoday/photoday/mail/developer/DeveloperEventListener.java
  server/src/main/java/com/photoday/photoday/mail/user/UserApplicationEvent.java
  server/src/main/java/com/photoday/photoday/mail/user/UserEventListener.java
  server/src/main/java/com/photoday/photoday/security/service/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/util/TempPassword.java
Labels: bug, 영롱, Feature

#167 Refactor/structure interface & Impl 구조 정리
  server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowService.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
  server/src/main/java/com/photoday/photoday/image/service/ImageService.java
  server/src/main/java/com/photoday/photoday/image/service/S3Service.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/controller/AuthController.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/photoday/photoday/security/service/AuthUserService.java
  server/src/main/java/com/photoday/photoday/security/service/impl/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/utils/UserDataResponder.java
  server/src/main/java/com/photoday/photoday/tag/controller/TagController.java
  server/src/main/java/com/photoday/photoday/tag/service/TagService.java
  server/src/main/java/com/photoday/photoday/tag/service/impl/TagServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
  server/src/test/java/com/photoday/photoday/follow/controller/FollowControllerTest.java
  server/src/test/java/com/photoday/photoday/helper/security/SecurityTestHelper.java
  server/src/test/java/com/photoday/photoday/image/controller/ImageControllerTest.java
  server/src/test/java/com/photoday/photoday/image/mapper/ImageMapperTest.java
  server/src/test/java/com/photoday/photoday/image/service/ImageServiceImplTest.java
  server/src/test/java/com/photoday/photoday/tag/controller/TagControllerTest.java
  server/src/test/java/com/photoday/photoday/user/controller/UserControllerTest.java
  server/src/test/java/com/photoday/photoday/user/service/UserServiceImplTest.java
  server/src/test/resources/application.yml
Labels: 현보

#168 [Feature] Upload Page 기능구현
  client/src/App.tsx
  client/src/components/Upload/Tag/TagItem.tsx
  client/src/components/Upload/Tag/TagList.tsx
  client/src/pages/Upload/Upload.styles.tsx
  client/src/pages/Upload/Upload.tsx
Labels: 은수, Feature

#170 [Feature] Redux userSlice 상태 추가
  client/src/api/Login.ts
  client/src/pages/Login/Login.tsx
  client/src/store/authSlice.ts
Labels: 아현, Feature

#175 [Bug] checkFollow 버그 수정
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/test/resources/application.yml
Labels: bug, 영롱

#171 [Feature] User page 기능 개발(유저 페이지 조회, 회원정보 수정, 비밀번호 변경, 회원탈퇴)
  client/src/api/User.ts
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserInfoArea/UserInfoTextarea/UserInfoTextarea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoTextarea/UserInfoTextarea.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/User/User.tsx
  client/src/store/store.ts
  client/src/store/userSlice.ts
Labels: 아현, Feature

#174 [Feature] 무한스크롤 및 태그 검색 기능 구현
  client/src/App.tsx
  client/src/api/Search.ts
  client/src/components/common/ImageCard/ImageCard.styles.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/components/common/Skeleton/ImageCardSkeleton.tsx
  client/src/context/ItemContext.tsx
  client/src/context/LoadintContext.tsx
  client/src/context/PageNumContext.tsx
  client/src/context/SearchContext.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Search/Search.styles.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Feature, Design

#186 Feat/test 시큐리티 인가 설정
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/tag/service/impl/TagServiceImpl.java
  server/src/test/java/com/photoday/photoday/follow/controller/FollowControllerTest.java
  server/src/test/java/com/photoday/photoday/image/controller/ImageControllerTest.java
  server/src/test/java/com/photoday/photoday/user/controller/UserControllerTest.java
Labels: Feature

#189 [Feature] Image filter 기능 구현
  client/src/App.tsx
  client/src/api/Search.ts
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/components/common/SelectBox/SelectBoxModal.tsx
  client/src/context/SearchContext.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Feature

#190 [Feature] User page 기능 구현(유저 페이지 조회, 회원정보 수정, 비밀번호 변경, 회원탈퇴)
  client/src/App.tsx
  client/src/api/Login.ts
  client/src/api/User.ts
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.styles.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.styles.tsx
  client/src/components/User/UserPageSubTitle/UserPageSubTitle.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/components/common/Pagination/Pagination.styles.tsx
  client/src/components/common/Pagination/Pagination.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Upload/Upload.tsx
  client/src/pages/User/User.styles.tsx
  client/src/pages/User/User.tsx
  client/src/store/authSlice.ts
Labels: 아현, Feature

#192 [Bug] checkFollow 버그 수정
  server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
  server/src/main/java/com/photoday/photoday/follow/dto/FollowDto.java
  server/src/main/java/com/photoday/photoday/follow/mapper/FollowMapper.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowService.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowServiceImpl.java
  server/src/test/java/com/photoday/photoday/follow/controller/FollowControllerTest.java
  server/src/test/java/com/photoday/photoday/follow/mapper/FollowMapperTest.java
  server/src/test/java/com/photoday/photoday/follow/service/FollowServiceImplTest.java
  server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java
Labels: bug, 현보, 영롱

#194 [Feat] 유저 이미지 삭제 기능 기본 이미지로 변경 #193
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: 민수, Feature

#195 [Feat] 메인 화면에서 좋아요 순으로 이미지 10개 조회 기능 추가
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/repository/ImageRepository.java
  server/src/main/java/com/photoday/photoday/image/service/ImageService.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
Labels: 영롱, Feature

#198 [Fix] 마이페이지 본인 확인 기능 추가
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/dto/UserDto.java
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: 민수, Feature

#196 [Feature] User page 기능 구현(Tap별 게시물 요청, 로그아웃, 게시물 없을 때 UI)
  client/src/api/User.ts
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/common/Header/HeaderModal.tsx
  client/src/components/common/Pagination/Pagination.styles.tsx
  client/src/pages/User/User.tsx
Labels: 아현, Feature

#200 [Feature] Main Page 인기있는 이미지 랜덤 출력 구현
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/components/common/ImageCard/MainImageCard.tsx
  client/src/components/common/Skeleton/MainSkeleton.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Feature, Design

#205 [Feat] 마이페이지 관리자 권한 기능 추가
  server/src/main/java/com/photoday/photoday/excpetion/ExceptionCode.java
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
  server/src/main/java/com/photoday/photoday/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/dto/UserDto.java
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: 민수, Feature

#206 Feat/test 로그인 테스트, 리팩토링
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/dto/LoginDto.java
  server/src/test/java/com/photoday/photoday/follow/mapper/FollowMapperTest.java
  server/src/test/java/com/photoday/photoday/follow/service/FollowServiceImplTest.java
  server/src/test/java/com/photoday/photoday/helper/security/SecurityTestHelper.java
  server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java
  server/src/test/java/com/photoday/photoday/image/mapper/ImageMapperTest.java
  server/src/test/java/com/photoday/photoday/security/controller/AuthControllerTest.java
  server/src/test/java/com/photoday/photoday/security/controller/LoginTest.java
  server/src/test/java/com/photoday/photoday/user/mapper/UserMapperTest.java
Labels: 현보

#208 [Fix] OAuth2 토큰 기능 수정, 인가 설정
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
Labels: 민수, Feature

#209 [Feature] Main Page 이미지 랜덤 출력 테스트 코드 수정
  client/src/components/common/ImageCard/ImageCard.styles.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
  client/src/components/common/ImageCard/ImageData.tsx
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/components/common/ImageCard/MainImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/pages/Main/Main.styles.tsx
Labels: 정호, Feature

#211 [Feature] Follow 기능, 프로필 이미지 삭제 기능 구현
  client/src/api/User.ts
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/User/UserFollwModal/ModalListItem.styles.tsx
  client/src/components/User/UserFollwModal/ModalListItem.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.styles.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/pages/User/User.tsx
  client/src/store/userSlice.ts
Labels: 아현, Feature

#213 [Feature] 소셜 로그인 기능 구현
  client/src/api/Login.ts
  client/src/components/Login/GoogleButton/GoogleButton.styles.tsx
  client/src/components/Login/GoogleButton/GoogleButton.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/User/User.tsx
  client/src/store/authSlice.ts
  client/src/store/store.ts
Labels: 아현, Feature

#214 [Feature] 좋아요, 북마크 기능 구현
  client/src/api/Image.ts
  client/src/api/Search.ts
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/HeaderModal.tsx
  client/src/components/common/ImageCard/ImageCard.styles.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
Labels: 정호, Feature

#216 [Fix] User기능 checkAdmin 메서드 오류 수정 #215
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: bug

#218 [Feature] 로그인, 로그아웃, 비밀번호 찾기 페이지 컴포넌트화, 로그인 상태 수정
  client/src/api/Login.ts
  client/src/components/AccountRecovery/AccountRecoverySection.tsx
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/Input/Input.tsx
  client/src/components/Login/LoginSection/LoginSection.styles.tsx
  client/src/components/Login/LoginSection/LoginSection.tsx
  client/src/components/Login/LoginValidationLogic/LoginValidationLogic.tsx
  client/src/components/Signup/SignupSection/SignupSection.styles.tsx
  client/src/components/Signup/SignupSection/SignupSection.tsx
  client/src/components/Signup/TermsGuideModal/TermsGuideModal.styles.tsx
  client/src/components/Signup/TermsGuideModal/TermsGuideModal.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/common/Header/HeaderModal.tsx
  client/src/pages/AccountRecovery/AccountRecovery.tsx
  client/src/pages/Login/Login.styles.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/store/authSlice.ts
Labels: 아현, Feature

#217 Feat/test 테스트에 수정사항 적용, 리팩토링
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/service/AuthUserService.java
  server/src/main/java/com/photoday/photoday/security/service/impl/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
  server/src/test/java/com/photoday/photoday/helper/snippets/RestDocsSnippets.java
  server/src/test/java/com/photoday/photoday/image/mapper/ImageMapperTest.java
  server/src/test/java/com/photoday/photoday/image/service/ImageServiceImplTest.java
  server/src/test/java/com/photoday/photoday/security/controller/AuthControllerTest.java
  server/src/test/java/com/photoday/photoday/security/controller/LoginTest.java
  server/src/test/java/com/photoday/photoday/user/controller/UserControllerTest.java
  server/src/test/java/com/photoday/photoday/user/mapper/UserMapperTest.java
  server/src/test/java/com/photoday/photoday/user/service/UserServiceImplTest.java
  server/src/test/resources/application.yml
Labels: bug, 현보

#221 [Feature] 메인페이지 랜덤 이미지 출력 기능 구현
  client/src/api/Image.ts
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/ImageCard/ImageCard.tsx
  client/src/components/common/ImageCard/ImageData.tsx
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/components/common/ImageCard/MainImageCard.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Main/Main.tsx
Labels: 정호, Feature

#224 [Review] 코드리뷰 후 수정사항 주석 추가
  server/src/main/java/com/photoday/photoday/dto/MultiResponseDto.java
  server/src/main/java/com/photoday/photoday/excpetion/ExceptionCode.java
  server/src/main/java/com/photoday/photoday/excpetion/ExceptionControllerAdvice.java
  server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
  server/src/main/java/com/photoday/photoday/follow/dto/FollowDto.java
  server/src/main/java/com/photoday/photoday/follow/entity/Follow.java
  server/src/main/java/com/photoday/photoday/follow/repository/FollowRepository.java
  server/src/main/java/com/photoday/photoday/follow/service/FollowServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/entity/Bookmark.java
  server/src/main/java/com/photoday/photoday/image/entity/Image.java
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
  server/src/main/java/com/photoday/photoday/image/repository/ImageRepository.java
  server/src/main/java/com/photoday/photoday/image/repository/ReportRepository.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
  server/src/main/java/com/photoday/photoday/mail/config/SimpleEmailSendable.java
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2FailureHandler.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/photoday/photoday/security/principaldetails/PrincipalDetailsService.java
  server/src/main/java/com/photoday/photoday/security/redis/service/RedisService.java
  server/src/main/java/com/photoday/photoday/security/service/impl/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java
  server/src/main/java/com/photoday/photoday/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/photoday/photoday/tag/entity/Tag.java
  server/src/main/java/com/photoday/photoday/tag/mapper/TagMapper.java
  server/src/main/java/com/photoday/photoday/tag/service/impl/TagServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/controller/UserController.java
  server/src/main/java/com/photoday/photoday/user/dto/UserDto.java
  server/src/main/java/com/photoday/photoday/user/entity/User.java
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: documentation

#223 [Feature] 이미지 변경 시, userProfileImage 값 변경
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
Labels: 아현, Feature

#222 [Design] Login page 반응형 css 추가
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/LoginSection/LoginSection.styles.tsx
  client/src/components/Signup/TermsGuideModal/TermsGuideModal.styles.tsx
  client/src/pages/Login/Login.styles.tsx
Labels: 아현, Design

#227 [Refactor] Feat/image 미사용 메서드 삭제, 변수명 변경, 주석 정리, 컬럼 옵션 추가, 메인 이미지 response 타입 변경
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/entity/Image.java
  server/src/main/java/com/photoday/photoday/image/repository/ReportRepository.java
  server/src/main/java/com/photoday/photoday/image/service/ImageService.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: enhancement

#233 [Fix] User 기능 수정
  server/src/main/java/com/photoday/photoday/follow/service/impl/FollowServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/service/AuthUserService.java
  server/src/main/java/com/photoday/photoday/security/service/impl/AuthUserServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/entity/User.java
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
  server/src/main/java/com/photoday/photoday/user/service/UserService.java
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: bug

#234 Hotfix/compile 긴급 컴파일 오류 해결
  server/src/main/java/com/photoday/photoday/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
Labels: bug, 영롱

#237 [Fix] Security 기능 수정
  server/src/main/java/com/photoday/photoday/follow/controller/FollowController.java
  server/src/main/java/com/photoday/photoday/follow/dto/FollowDto.java
  server/src/main/java/com/photoday/photoday/follow/repository/FollowRepository.java
  server/src/main/java/com/photoday/photoday/follow/service/impl/FollowServiceImpl.java
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/photoday/photoday/security/principaldetails/PrincipalDetailsService.java
  server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java
  server/src/test/java/com/photoday/photoday/follow/service/FollowServiceImplTest.java
  server/src/test/java/com/photoday/photoday/image/service/ImageServiceImplTest.java
Labels: bug

#231 [Design] User page 반응형 css 추가
  client/src/components/Login/Input/Input.styles.tsx
  client/src/components/Login/LoginSection/LoginSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.styles.tsx
  client/src/pages/User/User.styles.tsx
Labels: 아현, Design

#238 [Feature] image response에 myImage, checkAdmin 필드 추가 #73
  server/src/main/java/com/photoday/photoday/image/dto/ImageDto.java
  server/src/main/java/com/photoday/photoday/image/mapper/ImageMapper.java
Labels: 영롱, Feature

#239 [Feat] Security 인가 수정
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
Labels: 민수, Feature

#240 [Feature] 헤더 유저 프로필 리덕스 작업
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/components/common/Footer/Footer.styles.tsx
  client/src/components/common/Footer/Footer.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Search/Search.tsx
  client/src/store/authSlice.ts
  client/src/styles/Layout.tsx
Labels: 정호, Feature, Design

#243 :hammer: [Fix] 인가 수정, 프론트 Origin 추가
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
Labels: Feature

#244 [Fix] Feat/log Prometheus.yml target host 주소 변경
  server/Prometheus.yml
Labels: bug, 영롱

#248 [Fix] feat/user 관리자가 회원 삭제 요청시 ban처리로 로직 수정
  server/src/main/java/com/photoday/photoday/user/service/impl/UserServiceImpl.java
Labels: 영롱, Feature

#249 [Design] ImageCard styles 수정
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/common/ImageCard/ImageCard.styles.tsx
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/components/common/ImageCard/MainImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/components/common/Skeleton/ImageCardSkeleton.tsx
  client/src/components/common/Skeleton/MainSkeleton.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Design

#251 [Fix] 프론트 Origin 추가, 쿠키 도메인 수정
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/photoday/photoday/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/photoday/photoday/security/jwt/JwtProvider.java
  server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java
Labels: bug

#252 [Design] 헤더 반응형 구현
  client/src/components/common/Header/Header.styles.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/ImageCard/MainImageCard.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/components/common/SelectBox/SelectBox.style.tsx
  client/src/pages/Main/Main.styles.tsx
  client/src/pages/Search/Search.styles.tsx
  client/src/styles/Layout.tsx
Labels: 정호, Design

#263 🔨 [Update] 다운로드 이벤트핸들러 수정 #153
  client/src/pages/Detail/Detail.tsx
Labels: 은수, Feature

#266 [Feature] 검색페이지 태그 출력 기능 구현
  client/src/App.tsx
  client/src/api/Search.ts
  client/src/components/common/ImageCard/MainImageCard.tsx
  client/src/components/common/ImageCardList/ImageCardList.styles.tsx
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/components/common/SearchBar/SearchBar.styles.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/components/common/Skeleton/ImageCardSkeleton.tsx
  client/src/components/common/Skeleton/MainSkeleton.tsx
  client/src/context/LoadintContext.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Feature, Design

#268 [Feat] Detail page 기능구현
  client/src/components/Upload/Tag/TagItem.tsx
  client/src/pages/Detail/Detail.styles.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/DetailModal.tsx
  client/src/pages/Upload/Upload.tsx
Labels: 은수, Feature

#270 [Hotfix] user likeCount 버그 수정
  server/src/main/java/com/photoday/photoday/user/mapper/UserMapper.java
Labels: bug, 현보, 영롱

#271 [Feat] accessToken 만료 확인 API 추가
  server/src/main/java/com/photoday/photoday/security/configuration/SecurityConfiguration.java
  server/src/main/java/com/photoday/photoday/security/controller/AuthController.java
Labels: Feature

#276 [Feature] 액세스 토큰 만료 확인 로직 추가, 비회원 팔로우 아이콘 미노출
  client/index.html
  client/public/favicon.ico
  client/src/api/Auth.ts
  client/src/api/Login.ts
  client/src/api/User.ts
  client/src/components/Login/LoginSection/LoginSection.tsx
  client/src/components/Signup/SignupSection/SignupSection.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/User/UserFollwModal/ModalListItem.tsx
  client/src/components/User/UserFollwModal/UserFollwModal.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.styles.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/components/common/Header/HeaderModal.tsx
Labels: 아현, Feature

#281 [Update] 디테일 페이지 수정
  client/src/pages/Detail/Detail.styles.tsx
  client/src/pages/Detail/Detail.tsx
Labels: 은수, Feature

#278 [Feat] 이미지 다운 기능 추가
  server/src/main/java/com/photoday/photoday/image/controller/ImageController.java
  server/src/main/java/com/photoday/photoday/image/service/S3Service.java
  server/src/main/java/com/photoday/photoday/image/service/impl/S3ServiceImpl.java
  server/src/main/java/com/photoday/photoday/image/util/ImageUtils.java
Labels: 민수, Feature

#283 [Fix] image url 길이 버그, 중복된 태그 처리 수정
  server/src/main/java/com/photoday/photoday/image/entity/Image.java
  server/src/main/java/com/photoday/photoday/image/service/impl/ImageServiceImpl.java
  server/src/main/java/com/photoday/photoday/user/entity/User.java
Labels: bug, 영롱

#286 [Fix] OAuth2 주소 변경, 쿠키 도메인 수정
  server/src/main/java/com/photoday/photoday/security/handler/OAuth2SuccessHandler.java
  server/src/main/java/com/photoday/photoday/security/utils/CookieUtil.java
Labels: 민수, Feature

#284 [Feature] 기존 코드 수정
  client/index.html
  client/src/api/User.ts
  client/src/components/User/UserContentSection/UserContentSection.styles.tsx
  client/src/components/User/UserContentSection/UserContentSection.tsx
  client/src/components/User/UserInfoArea/UserInfoArea.tsx
  client/src/components/User/UserThumnailArea/UserThumnailArea.tsx
  client/src/components/common/Pagination/Pagination.tsx
Labels: 아현, Feature

#287 🐛 [Fix] Detail page bug fix #153
  client/src/pages/Detail/Detail.tsx
Labels: 은수, Feature

#289 [Feature] postLogin 수정
  client/src/api/Login.ts
Labels: 아현, Feature

#290 Hotfix/user report cascade 수정
  server/src/main/java/com/photoday/photoday/mail/developer/DeveloperEventListener.java
  server/src/main/java/com/photoday/photoday/user/entity/User.java
Labels: bug

#292 :hammer: [Fix] Oauth2 redirect-uri 설정
  server/src/main/resources/application.yml
Labels: Feature

#293 [Feature] filter 기본값 수정
  client/src/api/Search.ts
  client/src/components/common/ImageCardList/ImageCardList.tsx
  client/src/components/common/SearchBar/SearchBar.tsx
  client/src/components/common/SelectBox/SelectBox.tsx
  client/src/components/common/SelectBox/SelectBoxModal.tsx
  client/src/pages/Search/Search.tsx
Labels: 정호, Feature, Design

#294 [Feature] 태그 중복 필터링 추가, 디테일페이지 버그 수정
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/DetailModal.tsx
  client/src/pages/Upload/Upload.tsx
Labels: 은수, Feature

#295 [Docs] DockerFile 환경변수 추가
  server/docker-compose.yml
Labels: documentation
